In [10]:
import numpy as np

# Define the given vectors
vt=np.array([[2,-1,7,1],[3,4,-2,1],[1,0,1,0]])
print(vt)
# Perform SVD
U, s, V = np.linalg.svd(vt, full_matrices=False)

# Extract the smallest singular value and its corresponding right singular vector
smallest_singular_value = s[-1]
smallest_singular_vector = V[-1]

# Calculate the projection matrix onto the subspace spanned by the smallest singular vector
projection_matrix = np.outer(smallest_singular_vector, smallest_singular_vector)

# Calculate the projection of the vectors onto the subspace
projection = vt.dot(projection_matrix)

# Calculate the error in the approximation
error = np.linalg.norm(vt - projection, ord=2)

print("\nError in the approximation:", error)


[[ 2 -1  7  1]
 [ 3  4 -2  1]
 [ 1  0  1  0]]

Error in the approximation: 7.763833167832662
